### ISSUE TITLE
Why is the First Googling Method always inconclusive?

### ISSUE THREAD

**Issue by josephodeh** [zweg25/HQ#17]
I was able to use your code with my own and connect to the WebSocket of the game. I now have everything working: my bot gets the question and answers quicker than showing up on the phone, your three methods run and give me their answers, and my own methods run giving me almost always the same answers. However, the first method, 'Googling the question', always indicates that the results are inconclusive. I would be happy to work with you to figure out why this is occurring. Please respond with any reason why this happens.

**Comment by zweg25** [comment]
This is most likely because the questions being asked have to find the exact answer choices, which is sometimes not easy in a general google query.
