### ISSUE TITLE
Unable to upload file

### ISSUE THREAD

**Issue by Heros15582** [zweg25/HQ#2]
Im not very good with php so i am unsure if this is a problem with my API keys or the way the images saves, etc.
Error code posted below 
I am using localhost

`(
  "<br />",
  "<b>Warning</b>:  move_uploaded_file(./screenshot.png): failed to open stream: Permission denied in <b>/Applications/XAMPP/xamppfiles/htdocs/hq.php</b> on line <b>6</b><br />",
  "<br />",
  "<b>Warning</b>:  move_uploaded_file(): Unable to move '/Applications/XAMPP/xamppfiles/temp/phppXNKRf' to './screenshot.png' in <b>/Applications/XAMPP/xamppfiles/htdocs/hq.php</b> on line <b>6</b><br />",
  "There was an error uploading the file"
)`

**Comment by Jam101s** [comment]
@Heros15582 Did you get it to work for you
