### ISSUE TITLE
Windows instead of Mac?

### ISSUE THREAD

**Issue by tombets2424** [zweg25/HQ#6]
any ideas on how to tweak this for windows (10)? I would love to use this as it is ALOT more reliable then other bots out there.

Thanks, Tom.

**Comment by Sonishkan** [comment]
I think you could technically run it on a virtual macos

**Comment by MrARM** [comment]
You shouldn't even need to use macOS, you just need to use XAMPP and make a way to automate the screenshot

**Comment by alvinthomas135** [comment]
@MrARM Hey so used XAMPP and got it to work and all but i'm having trouble making a way to automate the screenshot.  Could you help me out?
